### PR TITLE
Added test case to verify IP address type

### PR DESCRIPTION
**Pull request by rahulmah**
This change is [Reviewable](https://reviewable.io/reviews/mkumatag/openbmc-automation/52)

### CODE REVIEW

**Comment by causten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[tests/test_networkd.robot, line 143 [r2]](https://reviewable.io:443/reviews/mkumatag/openbmc-automation/52#-KITAihAekPfGk6CdWLD:-KITAihBh1dxq6aCDkGK:241427769) ([raw file](https://github.com/mkumatag/openbmc-automation/blob/87bbbdec79dd1e4a8416570f32d70d10a84793ca/tests/test_networkd.robot#L143)):_

> ``` RobotFramework
> 
> 
> Get IP Address type with valid interface
> ```

This test case is assuming the interface is set to Static?  Rules of test cases require that the TC is not reliant on other test cases.  You should force the value then read it back.  OR check if it is either 'STATIC' or 'DYNAMIC'

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mkumatag/openbmc-automation/52)_

**Comment by rahulmah** [comment]
@causten : I have modified the test case to first force static ip address and then read address type back. Now it should looks good. Please mark it LGTM, if it looks good.

**Comment by causten** [comment]
I think the networkd code needs a rewrite now that we are better with robot.  The test cases should not hardcode IP's and MAC's.  When you hardcode the MAC I no longer can run the test suite on multiple systems at the same time.  Having said that the changes specific to this pull request are a step in the right direction   :lgtm:

<details><summary>

<i>Previously, rahulmah (Rahul Maheshwari) wrote…</i></summary>



> @causten : I have modified the test case to first force static ip address and then read address type back. Now it should looks good. Please mark it LGTM, if it looks good.
> </details>

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mkumatag/openbmc-automation/52#-:-KJaGn47VP9VrElGgGEz:-1921833982)_

**Comment by causten** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mkumatag/openbmc-automation/52)_

**Pull request merged**
