### PR TITLE
Test autostart policy for openbmc services

### PR DESCRIPTION
**Pull request by mkumatag**
This is to test https://github.com/openbmc/openbmc/pull/149

---

This change is [Reviewable](https://reviewable.io/reviews/mkumatag/openbmc-automation/19)

### CODE REVIEW

**Comment by causten** [comment]
Looks Good To Me

**Comment by mkumatag** [comment]
seems like https://github.com/openbmc/openbmc/pull/149 is not yet merged, will deliver the code once it is merged.

**Comment by anoo1** [comment]
:lgtm:

<details><summary>

<i>Previously, mkumatag (Manjunath A Kumatagi) wrote…</i></summary>



> seems like https://github.com/openbmc/openbmc/pull/149 is not yet merged, will deliver the code once it is merged.
> </details>

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mkumatag/openbmc-automation/19#-:-KIhCcbUhriSdcOnRCHP:1417088721)_

**Comment by rahulmah** [comment]
Before this automation code in merged below dev code need to be integrated.

https://github.com/openbmc/openbmc/pull/149

**Comment by mkumatag** [comment]
merging as openbmc/openbmc#149 merged to master now.

**Pull request merged**
